#!/usr/bin/env python

import os
import sys
from redbaron import RedBaron

def m18nify_file(file_path):
    red = RedBaron(open(file_path).read())

    for string in red("string"):
        print string


if __name__ == '__main__':
    files = sys.argv[1:]

    for f in files:
        if not os.path.exists(f):
            print "Error, file '%s' doesn't exists, abort" % f
            sys.exit(0)


    for f in files:
        m18nify_file(f)
